version: 2.0.{build}.1

environment:
  APPVEYOR_RDP_PASSWORD:
    secure: 0qKfXtTntKUwQoDfGF9/K2HwEvqUCXrEF89XngR6/ZU=

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2022

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

# init:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
- ps: >-    
    $env:NUGET_RESTORE_MSBUILD_ARGS = "/p:RestoreProjectFilterMode=""inclusionlist"""
    
    nuget restore AmethystWindows
    
    & "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.com" AmethystWindows\AmethystWindows.sln /build Release /project .\AmethystWindowsSetup\AmethystWindowsSetup.vdproj /projectconfig Release

test: off

artifacts:
- path: AmethystWindowsSetup\Release
  name: msi

deploy:
- provider: Webhook
  url: https://app.signpath.io/API/v1/698a531d-4078-4f30-953b-6a9e9892e338/Integrations/AppVeyor?ProjectSlug=amethystwindows&SigningPolicySlug=test-signing&ArtifactConfigurationSlug=v2
  authorization:
    secure: xCVRa1gtcPlfTZvZ2FA6890QXlY9SSPCdlUmcuwyEuzO7r1hjp0GpAn1UKe6E+xZW8y02VaNzPMXTv6sEeTIkw==

